#uvdesk_community_installation_wizard_check_requirements:
#    path:     /xhr/check-requirements
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::evaluateSystemRequirements
#    methods: [POST]
#
#uvdesk_community_installation_wizard_verify_database_credentials:
#    path:     /xhr/verify-database-credentials
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::verifyDatabaseCredentials
#    methods: [POST]
#
#uvdesk_community_installation_wizard_store_super_user_credentials:
#    path:     /xhr/intermediary/super-user
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::prepareSuperUserDetailsXHR
#    methods: [POST]
#
#uvdesk_community_installation_wizard_store_website_configuration:
#    path:     /xhr/website-configure
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::websiteConfigurationXHR
#
#uvdesk_community_installation_wizard_update_configurations_xhr:
#    path:     /xhr/load/configurations
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::updateConfigurationsXHR
#    methods: [POST]
#
#uvdesk_community_installation_wizard_migrate_database_schema_xhr:
#    path:     /xhr/load/migrations
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::migrateDatabaseSchemaXHR
#    methods: [POST]
#
#uvdesk_community_installation_wizard_populate_database_entities_xhr:
#    path:     /xhr/load/entities
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::populateDatabaseEntitiesXHR
#    methods: [POST]
#
#uvdesk_community_installation_wizard_create_default_super_user_xhr:
#    path:     /xhr/load/super-user
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::createDefaultSuperUserXHR
#    methods: [POST]
#
#uvdesk_community_installation_wizard_update_website_configuration:
#    path:     /xhr/load/website-configure
#    controller: Webkul\UVDesk\Setup\Controller\InstallationWizardXHR::updateWebsiteConfigurationXHR
#    methods: [POST]
